runtime: python311  # or python310, etc.
entrypoint: gunicorn -b :$PORT main:app

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

env_variables:
  FLASK_ENV: "production"
  FLASK_APP: "main.py"